defmodule Euler do

  @doc """
  If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

  Find the sum of all the multiples of 3 or 5 below 1000.
  """
  def p1 do
    test = for i <- 1..999,
          rem(i,3) == 0 or rem(i,5) == 0, do: i

    Enum.sum(test)
  end

  @doc """
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  """
  def p2 do
    stream = 1..999
    stream
    |> Stream.map(fn(i) -> fib(i) end)
    |> Stream.filter(fn(i) -> rem(i,2) == 0 end)
    |> Stream.take_while(fn(i) -> i <= 4_000_000 end)
    |> Enum.sum
  end
  defp fib(n) when n <= 1, do: 1
  defp fib(n), do: fib(n-2) + fib(n-1)


  @doc """
  The prime factors of 13195 are 5, 7, 13 and 29.

  What is the largest prime factor of the number 600851475143 ?
  """
  def p2 do
  end
end
